version: '3.8'

services:
  nestjs-api:
    image: nestjs-api
    build: . # ./Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URL: mongodb://mongo/nestjs_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
